package(default_visibility = ["//visibility:public"])

cc_library(
    name = "corge",
    srcs = ["corge.cc"],
    hdrs = ["corge.h"],
    deps = [
        ":grault",
    ],
)

cc_library(
    name = "grault",
    srcs = ["grault.cc"],
    hdrs = ["grault.h"],
    deps = [
        ":garply",
    ],
)

cc_library(
    name = "garply",
    srcs = ["garply.cc"],
    hdrs = ["garply.h"],
)
