load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "b8a1527901774180afc798aeb28c4634bdccf19c4d98e7bdd1ce79d1fe9aaad7",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "rules_testing",
    sha256 = "453630dd24f1c2915d2c178b06a8244ac09c7299cc344a75356548ff3d7aeeaf",
    strip_prefix = "rules_testing-0.1.0",
    url = "https://github.com/bazelbuild/rules_testing/releases/download/v0.1.0/rules_testing-v0.1.0.tar.gz",
)

new_local_repository(
    name = "repo2",
    path = "examples/repo2",
    build_file = "examples/repo2/BUILD",
)

new_local_repository(
    name = "repo1",
    path = "examples/repo1",
    build_file = "examples/repo1/BUILD",
)
